source "https://rubygems.org"

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem "active_model_serializers", "~> 0.10.0"
gem "devise"
gem "faker"
gem "puma", "~> 3.7"
gem "rails", "~> 5.1.2"
gem "simple_token_authentication", "~> 1.0"


group :development, :test do
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "rspec-rails", "~> 3.6"
  gem "sqlite3"
end

group :development do
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

group :test do
  gem "brakeman", require: false
  gem "bundler-audit"
  gem "database_cleaner"
  gem "factory_girl_rails", "~> 4.0"
  gem "rails_best_practices"
  gem "reek"
  gem "rspec-activemodel-mocks"
  gem "rspec-collection_matchers"
  gem "rubocop", require: false
  gem "rubocop-checkstyle_formatter", require: false
  gem "shoulda-matchers", "~> 3.1"
end

group :production do
  gem "pg", "0.20.0"
end
